services:
  - type: web
    name: club-africain-api
    env: node
    region: frankfurt
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    healthCheckPath: /api/matches
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3001"
